In [3]:
# MSE RMSE MAE MAPE
#Hataların Karesinin Ortalaması (MSE):
#Hataların Karesinin Ortalamasının Karekökü (RMSE):
#Hataların Mutlak Değerlerinin Ortalaması (MAE):
#Ortalama Mutlak Yüzde Hata (MAPE)

#https://kaggle.com/datasets/mirichoi0218/insurance

In [73]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,mean_absolute_percentage_error

In [11]:
df=pd.read_csv('insurance.csv')

In [13]:
df.head(5)

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [19]:
df=pd.get_dummies(df,columns=['sex','smoker','region'],drop_first=True)

In [21]:
df.head(5)

age     bmi  children      charges  sex_male  smoker_yes  region_northwest  \
0   19  27.900         0  16884.92400     False        True             False   
1   18  33.770         1   1725.55230      True       False             False   
2   28  33.000         3   4449.46200      True       False             False   
3   33  22.705         0  21984.47061      True       False              True   
4   32  28.880         0   3866.85520      True       False              True   

   region_southeast  region_southwest  
0             False              True  
1              True             False  
2              True             False  
3             False             False  
4             False             False

In [23]:
y=df[['charges']]
X=df.drop('charges',axis=1)

In [25]:
lm=LinearRegression()
model=lm.fit(X,y)

In [27]:
model.score(X,y)

0.7509130345985207

In [29]:
model.predict([[19,26,0,1,1,0,0,1]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[24517.93110714]])

In [31]:
model.predict([[19,27.900,0,1,1,0,0,1]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[25162.398669]])

In [33]:
df_hata=pd.DataFrame()

In [35]:
df_hata['y']=y

In [39]:
df_hata.head(3)

y
0  16884.9240
1   1725.5523
2   4449.4620

In [43]:
model.predict(X)

array([[25293.7130284 ],
       [ 3448.60283431],
       [ 6706.9884907 ],
       ...,
       [ 4149.13248568],
       [ 1246.58493898],
       [37085.62326757]])

In [45]:
y_tahmin=model.predict(X)

In [47]:
df_hata['tahmin']=y_tahmin

In [49]:
df_hata

y        tahmin
0     16884.92400  25293.713028
1      1725.55230   3448.602834
2      4449.46200   6706.988491
3     21984.47061   3754.830163
4      3866.85520   5592.493386
...           ...           ...
1333  10600.54830  12351.323686
1334   2205.98080   3511.930809
1335   1629.83350   4149.132486
1336   2007.94500   1246.584939
1337  29141.36030  37085.623268

[1338 rows x 2 columns]

In [51]:
df_hata['error']=y-y_tahmin

In [53]:
df_hata.head(10)

y        tahmin         error
0  16884.92400  25293.713028  -8408.789028
1   1725.55230   3448.602834  -1723.050534
2   4449.46200   6706.988491  -2257.526491
3  21984.47061   3754.830163  18229.640447
4   3866.85520   5592.493386  -1725.638186
5   3756.62160   3719.825799     36.795801
6   8240.58960  10659.961225  -2419.371625
7   7281.50560   8047.910607   -766.405007
8   6406.41070   8502.973920  -2096.563220
9  28923.13692  11884.637518  17038.499402

In [55]:
df_hata['squared_error']=df_hata['error']**2

In [61]:
df_hata.head(10)

y        tahmin         error  squared_error     abs_error
0  16884.92400  25293.713028  -8408.789028   7.070773e+07   8408.789028
1   1725.55230   3448.602834  -1723.050534   2.968903e+06   1723.050534
2   4449.46200   6706.988491  -2257.526491   5.096426e+06   2257.526491
3  21984.47061   3754.830163  18229.640447   3.323198e+08  18229.640447
4   3866.85520   5592.493386  -1725.638186   2.977827e+06   1725.638186
5   3756.62160   3719.825799     36.795801   1.353931e+03     36.795801
6   8240.58960  10659.961225  -2419.371625   5.853359e+06   2419.371625
7   7281.50560   8047.910607   -766.405007   5.873766e+05    766.405007
8   6406.41070   8502.973920  -2096.563220   4.395577e+06   2096.563220
9  28923.13692  11884.637518  17038.499402   2.903105e+08  17038.499402

In [59]:
df_hata['abs_error']=np.abs(df_hata['error'])

In [63]:
df_hata.head(10)

y        tahmin         error  squared_error     abs_error
0  16884.92400  25293.713028  -8408.789028   7.070773e+07   8408.789028
1   1725.55230   3448.602834  -1723.050534   2.968903e+06   1723.050534
2   4449.46200   6706.988491  -2257.526491   5.096426e+06   2257.526491
3  21984.47061   3754.830163  18229.640447   3.323198e+08  18229.640447
4   3866.85520   5592.493386  -1725.638186   2.977827e+06   1725.638186
5   3756.62160   3719.825799     36.795801   1.353931e+03     36.795801
6   8240.58960  10659.961225  -2419.371625   5.853359e+06   2419.371625
7   7281.50560   8047.910607   -766.405007   5.873766e+05    766.405007
8   6406.41070   8502.973920  -2096.563220   4.395577e+06   2096.563220
9  28923.13692  11884.637518  17038.499402   2.903105e+08  17038.499402

In [67]:
df_hata['percent_error']=np.abs((y-y_tahmin)/y)

In [69]:
df_hata.head(10)

y        tahmin         error  squared_error     abs_error  \
0  16884.92400  25293.713028  -8408.789028   7.070773e+07   8408.789028   
1   1725.55230   3448.602834  -1723.050534   2.968903e+06   1723.050534   
2   4449.46200   6706.988491  -2257.526491   5.096426e+06   2257.526491   
3  21984.47061   3754.830163  18229.640447   3.323198e+08  18229.640447   
4   3866.85520   5592.493386  -1725.638186   2.977827e+06   1725.638186   
5   3756.62160   3719.825799     36.795801   1.353931e+03     36.795801   
6   8240.58960  10659.961225  -2419.371625   5.853359e+06   2419.371625   
7   7281.50560   8047.910607   -766.405007   5.873766e+05    766.405007   
8   6406.41070   8502.973920  -2096.563220   4.395577e+06   2096.563220   
9  28923.13692  11884.637518  17038.499402   2.903105e+08  17038.499402   

   percent_error  
0       0.498006  
1       0.998550  
2       0.507371  
3       0.829205  
4       0.446264  
5       0.009795  
6       0.293592  
7       0.105254  
8       0.327260  
9       0.589096

In [71]:
df_hata.mean()

y                1.327042e+04
tahmin           1.327042e+04
error           -2.158860e-12
squared_error    3.650189e+07
abs_error        4.170887e+03
percent_error    4.203527e-01
dtype: float64

In [75]:
mean_squared_error(y,y_tahmin)

36501893.00741544

In [77]:
mean_absolute_error(y,y_tahmin)

4170.8868941635865

In [79]:
mean_absolute_percentage_error(y,y_tahmin)

0.42035268473727033